# Generated by Django 3.0.5 on 2020-05-07 14:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('po', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UrAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('procurement_date', models.DateField(default=datetime.datetime.now, null=True, verbose_name='date created')),
                ('product_type', models.CharField(max_length=55, null=True)),
                ('vendor_name', models.CharField(max_length=55)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='po.Branch')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='po.Po')),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=55)),
                ('procurement_date', models.DateField(default=django.utils.timezone.now, verbose_name='date created')),
                ('warranty_expiration', models.DateField(null=True, verbose_name='warranty expiration')),
                ('product_type', models.CharField(max_length=55)),
                ('invoice_number', models.IntegerField()),
                ('vendor_name', models.CharField(max_length=55)),
                ('status', models.CharField(default='Active', max_length=55)),
                ('notes', models.CharField(max_length=100)),
                ('serial_no', models.CharField(max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='po.Branch')),
                ('po', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='po.Po')),
            ],
        ),
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=50)),
                ('old_notes', models.CharField(max_length=200)),
                ('new_status', models.CharField(max_length=50)),
                ('new_notes', models.CharField(max_length=200)),
                ('modified_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Assets')),
                ('new_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_branch', to='po.Branch')),
                ('old_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_branch', to='po.Branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
